"""Refactor Role departments to M2M

Revision ID: 350ed6ea88ff
Revises: 67e47d055f82
Create Date: 2026-02-22 22:16:28.200426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '350ed6ea88ff'
down_revision: Union[str, None] = '67e47d055f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_department_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_department_id_fkey', 'roles', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
