"""Add department to Role

Revision ID: 67e47d055f82
Revises: 3cc0f2e46765
Create Date: 2026-02-22 22:10:14.848720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e47d055f82'
down_revision: Union[str, None] = '3cc0f2e46765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'roles', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'department_id')
    # ### end Alembic commands ###
