"""Add workflow models

Revision ID: a4bcc9dce621
Revises: d938300e995b
Create Date: 2026-02-23 10:49:01.009205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4bcc9dce621'
down_revision: Union[str, None] = 'd938300e995b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcements')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='公告标题'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='公告内容(富文本)'),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='发布人ID'),
    sa.Column('read_count', sa.INTEGER(), autoincrement=False, nullable=False, comment='阅读次数'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='announcements_author_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='announcements_pkey')
    )
    # ### end Alembic commands ###
